chexam/chexam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('exams/', include('exams.urls')),
    path('account/', include('accounts.urls')),
    path('', include('allauth.urls')),
]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

chexam/exams/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.results_page, name='results_page'),
    path('result/<int:pk>', views.result_details, name='result_details'),
    path('result/<int:pk>/verify/', views.verify_result, name='verify_result'),
    path('reclamations/', views.reclamations_page, name='reclamations_page'),
    path('problem/<int:pk>/validate/', views.validate_problem, name='validate_problem'),
    path('problem/<int:pk>/refuse/', views.refuse_problem, name='refuse_problem'),
    path('reclamation/<int:pk>/add_problem/', views.add_problem, name='add_problem'),
    path('add_solution/', views.add_scans, name='add_solution'),
    path('add_exam/', views.add_exam, name='add_exam'),
    path('list/', views.exams_list, name='exams_list'),
]

chexam/exams/models.py
from django.db import models
from django.db.models import Model
from django.apps import apps
from accounts.models import Teacher, Student


class Exam(Model):
    module_name = models.CharField(max_length=500)
    teacher = models.OneToOneField(Teacher, on_delete=models.CASCADE)
    date_passed = models.DateTimeField()
    date_created = models.DateTimeField(auto_now_add=True)
    solution = models.FileField(upload_to='Solutions', default=None, blank=True)

    def __str__(self):
        return f'{self.module_name}'


def folder_name(result, filename):
    return u'%s/%s/PDFs/_%s' % (str(result.exam.id), str(result.student),
                                filename)


class Result(Model):
    exam = models.ForeignKey(Exam, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    mark = models.FloatField()
    scan = models.FileField(upload_to=folder_name, default=None, blank=True)
    verified = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.student} _ {self.exam}'


class Reclamation(Model):
    result = models.OneToOneField(Result, on_delete=models.CASCADE)
    treated = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.result}'


# problem types
counting = 'counting'
miss_judging = 'miss_judging'
forgetting = 'forgetting'

PROBLEM_TYPE_CHOICES = [
    (counting, 'Counting'),
    (miss_judging, 'Miss Judging'),
    (forgetting, 'Forgetting'),
]


def folder_name2(Problem, filename):
    return u'%s/%s/Problems/_%s' % (str(Problem.reclamation.result.exam.id), str(Problem.reclamation.result.student),
                                    filename)


class Problem(Model):
    reclamation = models.ForeignKey(Reclamation, on_delete=models.CASCADE)
    comment = models.CharField(max_length=1500)
    approved = models.BooleanField(default=False)
    problem_type = models.CharField(
        max_length=30,
        choices=PROBLEM_TYPE_CHOICES,
        default=counting,
    )
    scan = models.FileField(upload_to=folder_name2, default=None, null=True, blank=True)

    def __str__(self):
        return f'{self.reclamation} - {self.comment[:10]}'

chexam/exams/forms.py
from django.forms.widgets import Select, Widget
from django import forms
from exams.models import Result, Exam, Problem


class addPdf(forms.ModelForm):
    scan = forms.FileField()

    def __init__(self, *args, **kwargs):
        super(addPdf, self).__init__(*args, **kwargs)
        self.fields['scan'].widget.attrs.update({
            'type': "file",
            'id': "students_files",
            'class': "hidden",
            'name': "students_files",
            # 'onchange':"form.submit()",
        })

    class Meta:
        model = Result
        fields = ['scan']
        widgets = {

        }


class addSolutionForm(forms.ModelForm):
    solution = forms.FileField(widget=forms.FileInput(attrs={
        'type': "file",
        'id': "correction",
        'class': "hidden",
        'name': "correction",
        # 'onchange':"form.submit()",
        'multiple': "true",

    }))

    class Meta:
        model = Exam
        fields = ['solution']


class imgForm(forms.ModelForm):
    solution = forms.FileField(widget=forms.FileInput(attrs={
        'type': "file",
        'id': "screenshot",
        'class': "",
        'name': "screenshot",
        # 'onchange':"form.submit()",
        'multiple': "false",

    }))

    class Meta:
        model = Problem
        fields = ['scan']

chexam/exams/views.py
from email.errors import MultipartInvariantViolationDefect
import json
from django.core.files.storage import default_storage
import glob, sys
from exams.forms import addPdf, addSolutionForm

import os
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.views.decorators.http import require_POST

from .forms import imgForm
from .models import Result
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect
from .models import Result, Reclamation, Problem, Exam
from accounts.models import Teacher, Student
from pdf2image import convert_from_path


def is_teacher(user):
    return Teacher.objects.filter(user=user).exists()


def is_student(user):
    return Student.objects.filter(user=user).exists()


@login_required
def results_page(request):
    if request.user.is_staff:
        return redirect("exams_list")

    if is_teacher(request.user):
        return redirect("reclamations_page")

    if request.user.is_staff:
        return redirect("add_exam")

    student = request.user.student
    results = student.result_set.all()

    context = {
        'results': results
    }
    return render(request, "exams/results_page/index.html", context=context)


@login_required
def exams_list(request):
    if not request.user.is_staff:
        return redirect('results_page')

    exams = Exam.objects.all()

    context = {'exams': exams}
    return render(request, 'exams/list/index.htm', context=context)


@login_required
def result_details(request, pk):
    result = get_object_or_404(Result, id=pk)
    if is_student(request.user) and result.student == request.user.student \
            or (is_teacher(request.user) and result.exam.teacher == request.user.teacher):
        problems = Problem.objects.filter(reclamation__result=result)

        import glob
        ps = glob.glob(rf"media/{result.exam.id}/{result.student}/PDFs/*.jpg")
        context = {
            'is_teacher': is_teacher(request.user),
            'problems': problems,
            'result': result,
            'images': [str(p) for p in ps]
        }
        return render(request, "exams/result_details/result_details.html", context=context)

    raise Http404


import os
import shutil


def convertPDFToImg2(pdfLoc, destin):
def convertPDFToImg2(pdfLoc,destin):
    temp = list(pdfLoc)
    temp[0] = ''
    pdfLoc = "".join(temp)

    images = convert_from_path(pdfLoc, 500)
    images = convert_from_path(pdfLoc, 500, poppler_path=r'C:\Program Files\poppler-0.67.0\bin')
    for i in range(len(images)):
        images[i].save('page' + str(i) + '.jpg', 'JPEG')
        shutil.move('page' +str(i)+'.jpg', destin)
    
from pdf2image import convert_from_path
import pytesseract
import  cv2
pytesseract.pytesseract.tesseract_cmd = 'C:\\Program Files\\Tesseract-OCR\\tesseract.exe'

def convertPDFToImg(pdfLoc):
    temp = list(pdfLoc)
    temp[0] = ''
    pdfLoc = "".join(temp)
    images = convert_from_path(pdfLoc,500, poppler_path=r'C:\Program Files\poppler-0.67.0\bin')
    for i in range(len(images)):
        images[i].save('page'+ str(i) +'.jpg', 'JPEG')
def extractKey(data:str):
    key = ""
    for line in data.splitlines():
        line.replace(' ','')
        line = line.lower()
        if 'matricule' in line:
            i = line.index('matricule')+len('matricule')
            while i<len(line):
                start = True
                if line[i].isnumeric():
                    key+=line[i]
                    i+=1
                    start = False
                else:
                    if not start:
                        return int(key)
                    else:
                        i+=1
            return key
def extractDetails(data):
    dets = {"nom":"","prenom":"","groupe":""}
    for line in data.splitlines():
        line = line.lower()
        for word in dets.keys():

            if word in line:
                i = line.index(word) + len(word)+1
                start = True
                while i < len(line):
                    if not line[i].isalpha():
                        if not start:
                            break
                        i+=1
                    else:
                        dets[word]+=line[i]
                        i+=1
                        start = False
            if word=="groupe":
                return dets
def treatImg(imgLoc,mat):

    img = cv2.imread(imgLoc)
    img = cv2.cvtColor(img,cv2.COLOR_BGR2RGB)
    hImg, wImg,r = img.shape

    data = pytesseract.image_to_string(img)
    print(data)
    mat=extractKey(data)
    print(extractKey(data))
    print(extractDetails(data))
    return extractKey(data)

@login_required
def add_scans(request):
    teacher = request.user.teacher
    sol_form = addSolutionForm(request.POST, request.FILES)
    scan_form = addPdf(request.POST, request.FILES)
    if request.method == "POST":
         
            test_student=get_object_or_404(Student,matricule='111') 
          
            exam = Exam.objects.get(teacher=teacher)
            if Result.objects.filter(student=test_student).exists():
                Result.objects.filter(student=test_student).delete()  
            result=Result(student=test_student,exam=exam,mark=0.0)
            
            scan_form = addPdf(request.POST, request.FILES,instance=result)   
            if scan_form.is_valid():
                scan_form.save()

                file_p=Result.objects.get(student=test_student)
                file_path=rf'{file_p.scan.url}'
                temp = list(file_path)
                temp[0] = ''

                file_pat = "".join(temp)
                convertPDFToImg(file_path)
                mat=0
                treatImg(r'page0.jpg',str(mat))
                if mat==None:
                    mat='19831243'
                student=get_object_or_404(Student,matricule=mat)
                result2=Result(student=student,exam=exam,mark=1)
                scan_form = addPdf(request.POST, request.FILES,instance=result2)  
                if scan_form.is_valid():
                    scan_form.save()
                result2.save()
                file_path=rf'{file_p.scan.url}'
                destin=rf'media/{exam.id}/{student}/PDFs/'
                convertPDFToImg2(file_path,destin)
                return redirect("reclamations_page")
            if name=='sol_btn' : 
                        exam = Exam.objects.get(teacher=teacher)
                        sol_form = addSolutionForm(request.POST, request.FILES,instance=exam)
                        if sol_form.is_valid():
                            sol_form.save()
                            return redirect("reclamations_page")
    context = {
        'sol_form': sol_form,
        'scan_form': scan_form
    }
    return render(request, "exams/add_solution/index.html", context=context)



@login_required
def reclamations_page(request):
    teacher = request.user.teacher
    reclamations = Reclamation.objects.filter(result__exam__teacher=teacher, treated=False)
    form = addPdf(request.POST, request.FILES)
    if is_teacher(request.user):
        exam = get_object_or_404(Exam, teacher=teacher)
        student = get_object_or_404(Student, matricule='111')
        if request.method == "POST" and 'scansub' in request.POST:
            form = addPdf(request.POST, request.FILES,
                          initial={'exam': exam, 'student': student})  # Do not forget to add: request.FILES
            result = Result(exam=exam, student=student, mark=0.33)
            result.save()
            if form.is_valid():
                # Do something with our files or simply save them
                # if saved, our files would be located in media/ folder under the project's base folder

                form.student = student
                form.save()
    context = {
        'reclamations': reclamations,
        'form': form
    }
    return render(request, "exams/reclamations_page/index.html", context=context)


@login_required
def verify_result(request, pk):
    try:
        result = get_object_or_404(Result, id=pk)
        pdf_link = result.scan.url
        images = f"./{result.scan.url}"
        images_link = f"{images}/Photos"

        if is_student(request.user) and result.student == request.user.student \
                or is_teacher(request.user) and result.exam.teacher == request.user.teacher:
            if request.method == "POST":
                result.verified = True
                result.reclamation.treated = True
                result.reclamation.save()
                result.save()
        return redirect("result_details", pk=result.reclamation.result.id)
    except:
        pass
    return redirect("results_page")


@login_required
def refuse_problem(request, pk):
    try:
        problem = get_object_or_404(Problem, id=pk)

        if is_teacher(request.user) and problem.reclamation.result.exam.teacher == request.user.teacher:
            if request.method == "POST":
                problem.approved = False
                problem.save()
        return redirect("result_details", pk=problem.reclamation.result.id)
    except:
        pass
    return redirect("results_page")


@login_required
def validate_problem(request, pk):
    try:
        problem = get_object_or_404(Problem, id=pk)
        print(is_teacher(request.user) and problem.reclamation.result.exam.teacher == request.user.teacher)
        if is_teacher(request.user) and problem.reclamation.result.exam.teacher == request.user.teacher:
            if request.method == "POST":
                problem.approved = True
                problem.save()
                return redirect("result_details", pk=problem.reclamation.result.id)
        pass
    except:
        pass
    return redirect("results_page")


@login_required
@require_POST
def add_problem(request, pk):
    user = request.user
    message = {}
    # sol_form = imgForm(request.POST, request.FILES)

    try:

chexam/exams/templates/exams/result_details/components/student_view/index.html
<div id="main-content">
    {% include 'exams/result_details/components/student_view/pdfs.html' with student_view=True %}
    {% include 'exams/result_details/components/student_view/report_form.html' %}
</div>
{% include 'exams/result_details/components/student_view/problem_form.html' %}

<script>
    const addProblemFormOverlay = document.querySelector("#add-problem-form-overlay");
    const reportBtn = document.querySelector("#report-btn");
    const closeFormBtn = document.querySelector("#close-form-btn");
    const mainContent = document.querySelector("#main-content");

    reportBtn.addEventListener('click', function () {
        addProblemFormOverlay.classList.remove("hidden");
        mainContent.classList.add("hidden");
    });

    closeFormBtn.addEventListener('click', function () {
        addProblemFormOverlay.classList.add("hidden");
        mainContent.classList.remove("hidden");
    });
</script>

chexam/exams/templates/exams/result_details/components/student_view/pdfs.html
<div id="pdfs" class="flex flex-row space-x-10 mt-4 justify-center">
    <div class="flex flex-col items-center justify-center space-y-7">
        <div class="w-96 bg-gray-100 rounded-md shadow-lg">
            <embed id="cpt" src="{{ result.exam.solution.url }}" width="100%" height="2100px"
                   style="max-height: 550px;"/>
        </div>
        {% if not result.verified and student_view %}
            <button id="report-btn"
                    class="flex space-x-2 items-center justify-center transition-all text-red-600 hover:text-white hover:bg-red-600 bg-white py-1.5 rounded-lg bg-opacity-40 px-3">
                <i class="fa-solid fa-triangle-exclamation "></i>
                <span class=" font-semibold">Report</span>
            </button>

        {% endif %}
    </div>

    <div class="flex flex-col items-center justify-center space-y-7">
        <div class="w-96 bg-gray-100 rounded-md shadow-lg">
            <embed id="cpt" src="{{ result.scan.url }}" width="100%" height="2100px" style="max-height: 550px;"/>
        </div>
        {% if not result.verified and student_view %}
            <form action="{% url 'verify_result' result.id %}" method="post">
                {% csrf_token %}
                <button type="submit"
                        class="flex space-x-2 items-center transition-all text-green-600 hover:bg-green-600 hover:text-white  justify-center bg-white py-1.5 rounded-lg bg-opacity-40 px-3">
                    <i class="fa-solid fa-check"></i>
                    <span class=" font-semibold">Verify</span>
                </button>
            </form>
        {% endif %}
    </div>

</div>

chexam/exams/templates/exams/result_details/components/student_view/problem.html
<div class="report-modal shadow-lg  w-[90%] rounded-xl py-4 px-12 card">
    <div class="w-full flex justify-between">
        <div class="cropped-img-reclamation overflow-hidden h-20 w-1/2 rounded-md bg-white ring-1">
            {% if problem.scan %}
                <img src="{{ problem.scan.url }}" class="w-full" alt=""/>
            {% endif %}
            {% if not problem.scan %}
                No screenshot
            {% endif %}
        </div>

        <div class="flex justify-center items-center space-x-4">
            {% if not result.reclamation.treated %}
                <span class=" space-x-4 my-auto text-gray-600 font-semibold text-center  px-4 w-32 hover:text-white hover:bg-gray-600 transition-all py-3 rounded-xl flex justify-center items-center bg-white">
                    <i class="fa-solid fa-spinner text-lg"></i>
                    <span>
                        Pending
                    </span>
                </span>
            {% endif %}

            {% if result.reclamation.treated and not problem.approved %}
                <span class=" space-x-4 my-auto text-red-600 font-semibold text-center  px-4 w-32 hover:text-white hover:bg-red-600 transition-all py-3 rounded-xl flex justify-center items-center bg-white">
                    <i class="fa-solid fa-remove  text-lg"></i>
                    <span>
                        Refused
                    </span>
                      </span>
            {% endif %}
            {% if result.reclamation.treated and problem.approved %}
                <span class=" space-x-3 text-green-600 font-semibold text-center w-32 px-4 hover:text-white hover:bg-green-600 transition-all py-3 rounded-xl flex justify-center items-center bg-white">
                    <i class="fa-solid fa-check text-lg"></i>
                    <span>
                        Validated
                    </span>
                </span>
            {% endif %}
        </div>
    </div>
    <div class="message mt-3 bg-white ring-1 px-2 rounded-md w-full h-fit min-h-20 py-2 text-sm">
        <span class="text-blue-500">{{ problem.get_problem_type_display }} : </span>{{ problem.comment }}
    </div>
</div>

chexam/exams/templates/exams/result_details/components/student_view/problem_form.html
{% load static %}

<div id="add-problem-form-overlay" class="relative hidden w-full h-full" style="z-index: 300">
    <div class="fixed w-full h-full top-0 left-0 flex flex-col items-center justify-center">
        <div class="relative add-problem-form cardrect w-[60vh] overflow-y-auto max-h-[60vh] space-y-6 flex flex-col  card space-x-2  shadow-lg w-2/3 px-6 py-5 rounded-lg">
            <button id="close-form-btn" class="absolute p-2 top-3 right-4">
                <i class="fa fa-close fa-xl"></i>
            </button>
            <h1 class="font-bold text-3xl text-center">Report a mistake</h1>
            <div id="pages-container" class="flex flex-row justify-start space-x-2">

                {% for image in images %}
                    <button class="w-10" id="page-{{ forloop.counter }}">
                        <span>{{ forloop.counter }}</span>
                        <img src="/{{ image }}" class="w-full">
                    </button>
                {% endfor %}
            </div>
            <div class="flex flex-row space-x-5 justify-start items-start">
                <div class="capture overflow-hidden rounded-lg w-60 h-28 shadow-lg bg-slate-700">
                    <img class="cropped overflow-hidden" alt=""  >
                </div>
                <button class="capture rounded-lg flex  w-28 h-28 shadow-lg items-center justify-center bg-[#474F93]">
                    <img src="{% static 'imgs/add.svg' %}" class="h-12 w-12" alt="">
                </button>
            </div>
            <form  enctype="multipart/form-data" id="add-problem-form" method="post" action="{% url 'add_problem' result.reclamation.id %}">
                <div class="description items-start">
                    <label>
                    <textarea name="comment" placeholder="Comment"
                              class="text-sm p-2 text-left   rounded-lg shadow-xl w-11/12" rows="2"></textarea>
                    </label>
                    <label>
                        <div class="flex justify-center">
                            <div class="mb-3 xl:w-96">
                                <select name="problem_type"
                                        class="form-select appearance-none
      block
      w-full
      px-3
      py-1.5
      text-base
      font-normal
      text-gray-700
      bg-white bg-clip-padding bg-no-repeat
      border border-solid border-gray-300
      rounded
      transition
      ease-in-out
      m-0
      focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none" aria-label="Default select example">
                                    <option value="counting" selected>Counting</option>
                                    <option value="miss_judging">Miss Judging</option>
                                    <option value="forgetting">Forgetting</option>
                                </select>
                            </div>
                        </div>
                    </label>
                </div>

 <a href=""
      class="download block w-[120px] bg-[#474F93] px-5 rounded-lg text-white justify-start py-2 font-semibold space-x-2 flex flex-row items-center">Download</a>
                <input type="file" name="screenshot">

                <div class="buttons flex justify-end">
                    <button type="submit"
                            class="bg-[#474F93] px-5 rounded-lg text-white justify-start py-2 font-semibold space-x-2 flex flex-row items-center">
                        <img src="{% static 'imgs/send.svg' %}" class="w-5" alt=""><span>Send</span></button>
                </div>
                <div id="form-response" class="text-dark mt-4">

                </div>
            </form>
        </div>
    </div>
</div>


<style>
    .add-problem-form {
        animation: forwards upupandaway .3s ease-in;
    }

    @keyframes upupandaway {
        0% {
            transform: translateY(300px);
        }

        100% {
            transform: translateY(0);
        }
    }
</style>

chexam/exams/templates/exams/result_details/components/student_view/report_form.html
<div id="problems-content">
    <div id="problems" class="list space-y-5 mt-5 flex flex-col custom-scroll">
        {% for problem in problems %}
            {% include 'exams/result_details/components/student_view/problem.html' with problem=problem %}
        {% endfor %}
    </div>
    {% if not result.verified %}
        {% load static %}
        <script type="module" src="{% static 'js/exams/result_detail.js' %}"></script>
        <script type="module" src="{% static 'js/exams/crop.js' %}"></script>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropper/2.3.4/cropper.min.css"/>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/cropperjs/0.8.1/cropper.min.js"></script>

    {% else %}
        Your result is verified
    {% endif %}
</div>